# -------
# Library
# -------

library:
  name: ComposeDialogs
  api: 21
  github: MFlisar/ComposeDialogs
  maven: io.github.mflisar.composedialogs
  maven-main-library: core
  multiplatform: true
  platforms:
    - jvm
    - android
    - ios
  screenshots: 
    - name: color
      images:
        - ./screenshots/color/demo_color1.jpg
        - ./screenshots/color/demo_color2.jpg
        - ./screenshots/color/demo_color3.jpg
        - ./screenshots/color/demo_color4.jpg
    - name: date
      images:
        - ./screenshots/date/demo_calendar1.jpg
        - ./screenshots/date/demo_calendar2.jpg
        - ./screenshots/date/demo_calendar3.jpg
    - name: info
      images:
        - ./screenshots/info/demo_info1.jpg
        - ./screenshots/info/demo_info2.jpg
        - ./screenshots/info/demo_info3.jpg
        - ./screenshots/info/demo_info4.jpg
    - name: input
      images:
        - ./screenshots/input/demo_input1.jpg
        - ./screenshots/input/demo_input2.jpg
    - name: list
      images:
        - ./screenshots/list/demo_list1.jpg
        - ./screenshots/list/demo_list2.jpg
        - ./screenshots/list/demo_list3.jpg
        - ./screenshots/list/demo_list4.jpg
        - ./screenshots/list/demo_list5.jpg
        - ./screenshots/list/demo_list6.jpg
        - ./screenshots/list/demo_list7.jpg
    - name: menu
      images:
        - ./screenshots/menu/demo_menu1.jpg
    - name: number
      images:
        - ./screenshots/number/demo_number1.jpg
        - ./screenshots/number/demo_number2.jpg
        - ./screenshots/number/demo_number3.jpg
    - name: progress
      images:
        - ./screenshots/progress/demo_progress1.jpg
        - ./screenshots/progress/demo_progress2.jpg
    - name: time
      images:
        - ./screenshots/time/demo_time1.jpg
        - ./screenshots/time/demo_time2.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.3 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.6 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.1 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: true

# ------------
# Groups
# ------------

groups:
  - name: core
    label: Core
    gradle-comment: core
  - name: modules
    label: Modules
    gradle-comment: dialog modules

# ------------
# Modules
# ------------

modules:
  - name: core
    group: core
    description: provides all the basic dialog classes and styles
    optional: false
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies:
      - name: Compose Unstyled (core)
        link: https://github.com/composablehorizons/compose-unstyled/
        version: 1.20.1
  - name: dialog-billing
    group: modules
    description: provides a simple list dialog to buy in app products
    optional: true
    platforms:
      - android
    platforms-info: only exists for android as it is based on googles billing library
    dependencies:
      - name: KotBilling
        link: https://github.com/MFlisar/Kotbilling
        version: 0.8.1
  - name: dialog-color
    group: modules
    description: provides a color dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-date
    group: modules
    description: provides a date picker dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-info
    group: modules
    description: provides an info dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-input
    group: modules
    description: provides an input dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-list
    group: modules
    description: provides a list dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-menu
    group: modules
    description: provides a menu dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-number
    group: modules
    description: provides a number picker dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-progress
    group: modules
    description: provides a progress dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []
  - name: dialog-time
    group: modules
    description: provides a time picker dialog
    optional: true
    platforms:
      - jvm
      - android
      - ios
    platforms-info: ""
    dependencies: []