# -------
# Library
# -------

library:
  name: ComposeDialogs
  api: 21
  github: MFlisar/ComposeDialogs
  maven: io.github.mflisar.composedialogs
  maven-main-library: core
  multiplatform: true
  screenshots:
    - name: Info Dialog
      images:
        - ./screenshots/demo_info1.jpg
        - ./screenshots/demo_info2.jpg
        - ./screenshots/demo_info3.jpg
        - ./screenshots/demo_info4.jpg
    - name: Input Dialog
      images:
        - ./screenshots/demo_input1.jpg
        - ./screenshots/demo_input2.jpg
    - name: Number Dialog
      images:
        - ./screenshots/demo_number1.jpg
        - ./screenshots/demo_number2.jpg
        - ./screenshots/demo_number3.jpg
    - name: Date Dialog
      images:
        - ./screenshots/demo_calendar1.jpg
        - ./screenshots/demo_calendar2.jpg
        - ./screenshots/demo_calendar3.jpg
    - name: Time Dialog
      images:
        - ./screenshots/demo_time1.jpg
        - ./screenshots/demo_time2.jpg
    - name: Color Dialog
      images:
        - ./screenshots/demo_color1.jpg
        - ./screenshots/demo_color2.jpg
        - ./screenshots/demo_color3.jpg
    - name: List Dialog
      images:
        - ./screenshots/demo_list1.jpg
        - ./screenshots/demo_list2.jpg
        - ./screenshots/demo_list3.jpg
        - ./screenshots/demo_list4.jpg
        - ./screenshots/demo_list5.jpg
        - ./screenshots/demo_list6.jpg
        - ./screenshots/demo_list7.jpg
    - name: Menu Dialog
      images:
        - ./screenshots/demo_menu1.jpg
    - name: Progress Dialog
      images:
        - ./screenshots/demo_progress1.jpg
        - ./screenshots/demo_progress2.jpg
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

# optional
dependencies:
  compose:
    cmp: 1.7.3
    compose: 1.7.5
    material3: 1.3.1
    experimental: true

# -------------
# Module
# -------------

# GRUPPEN - optional: nur bei mehreren Modulen benötigt!
groups:
  - name: core
    label: Core
    gradle-comment: core 
  - name: modules
    label: Modules
    gradle-comment: dialog modules

modules:
  - name: core
    group: core
    description: the core module - must always be included
    optional: false
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies:         # optionales Array
      - name: Compose Unstyled (core)
        link: https://github.com/composablehorizons/compose-unstyled/
        version: 1.20.0
  - name: dialog-info
    group: modules
    description: an info dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-input
    group: modules
    description: a input dialog (string and numerical)
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []  
  - name: dialog-number
    group: modules
    description: a number picker dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-date
    group: modules
    description: a date picker dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-time
    group: modules
    description: a time picker dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-color
    group: modules
    description: a color picker dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-list
    group: modules
    description: a list dialog (with filtering, lazy loading and more)
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-menu
    group: modules
    description: a menu dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-progress
    group: modules
    description: a progress dialog
    optional: true
    platforms:
      android: true
      ios: true
      jvm: true
      info:
    dependencies: []
  - name: dialog-billing
    group: modules
    description: a dialog that offers an in-app purchase list
    optional: true
    platforms:
      android: true
      ios: false
      jvm: false
      info: only exists for android as it is based on googles billing library
    dependencies:
      - name: KotBilling
        link: https://github.com/MFlisar/KotBilling
        version: 0.8.1