[versions]

materialize =				"1.2.0"

# ---------
# libraries
# ---------

[libraries]

materialize =			        			{ module = "com.mikepenz:materialize", 												version.ref = "materialize" }

# -------
# bundles
# -------

[bundles]