# Java
java-version: 17

# Developer
developer:
  name: Michael Flisar
  mail: mflisar.development@gmail.com
  maven-id: mflisar
  github-user-name: MFlisar

# Readme
readme:
  screenshots:
    exclude-root: true
    group-by-folder: true
    excluded-folders: []
    excluded-images: []