site_name: MKDocs Example
site_url: https://mflisar.github.io/ComposeDialogs/
repo_url: https://github.com/MFlisar/ComposeDialogs
repo_name: mflisar/ComposeDialogs

copyright: Copyright &copy; 2024 Michael Flisar

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate    
      primary: black
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  #custom_dir: overrides
  features:
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    #- navigation.expand
    - navigation.path
    - navigation.footer
    #- navigation.indexes
    - toc.follow
    #- toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/git-alt

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
      restrict_base_path: false
      #base_path: ["docs/"]
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - def_list
  #- pymdownx.tasklist:
  #    custom_checkbox: true
      
# Plugins
plugins:
  - search
  #- social
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true
  #- optimize
  #- privacy
  #- typeset
  - macros:
      include_dir: _include
      include_yaml:
        - project: _data/project.yml
        - other_projects: _data/other-projects.yml
  - glightbox:
      skip_classes:
         - exclude-glightbox
        
# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mflisar
  #generator: false

extra_css:
  - stylesheets/extra.css
  
# nav
nav:
  - About: index.md
  - General:
    - Dependencies: dependencies.md
    - Setup: setup.md
    - Usage: usage.md
  - Modules:
    - Core: modules/core.md
    - Dialog Info: modules/dialog-info.md
    - Dialog Input: modules/dialog-input.md
    - Dialog Number: modules/dialog-number.md
    - Dialog Date: modules/dialog-date.md
    - Dialog Time: modules/dialog-time.md
    - Dialog Color: modules/dialog-color.md
    - Dialog List: modules/dialog-list.md
    - Dialog Menu: modules/dialog-menu.md
    - Dialog Progress: modules/dialog-progress.md
    - Dialog Billing: modules/dialog-billing.md
  - Advanced:
    - Dialog Styles: advanced/styles.md
    - Events: advanced/events.md
    - Buttons: advanced/buttons.md
    - Options: advanced/options.md
    - Custom Dialog: advanced/custom-dialog.md
  - Migration:
    - Version 2: migration/v2.md
  - More:
    - Other Libraries: other-libraries.md
    - About Me: me.md
